/* Aircraft2Sell — Supabase Client */
var _SB='https://hlivysnlzlqdjcigqgvk.supabase.co',_SK='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsaXZ5c25semxxZGpjaWdxZ3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMjIwNzAsImV4cCI6MjA4OTc5ODA3MH0.5tKQLlx9LsSujgILJKpmo__ByHorH6KuLyznE-mBVwU';
async function sbReq(m,t,p,b){var url=_SB+'/rest/v1/'+t+(p?'?'+p:'');var h={'apikey':_SK,'Authorization':'Bearer '+_SK,'Content-Type':'application/json','Prefer':'return=representation'};var r=await fetch(url,{method:m,headers:h,body:b?JSON.stringify(b):undefined});var tx=await r.text();if(!r.ok)throw new Error(tx);return tx?JSON.parse(tx):[];}
function sbGet(t,p){return sbReq('GET',t,p);}
function sbPost(t,b){return sbReq('POST',t,null,b);}
function sbPatch(t,p,b){return sbReq('PATCH',t,p,b);}
function sbDelete(t,p){return sbReq('DELETE',t,p);}
function sbRowListing(r){var ph=Array.isArray(r.photos)?r.photos:[];var th=ph.length?ph[0]:(r.icon||'✈');var sym={EUR:'€',USD:'$',GBP:'£',CHF:'Fr'}[r.currency||'EUR']||'€';var pn=r.price&&!isNaN(Number(r.price))?Number(r.price):null;return{id:r.id,make:r.make||'',model:r.model||'',year:r.year||'',price:r.price||'--',priceDisplay:pn?sym+pn.toLocaleString('fr-FR'):(r.price||'--'),currency:r.currency||'EUR',category:r.category||'light',catDisp:r.category||'light',airport:r.airport||'',loc:r.airport||r.country||'--',country:r.country||'',desc:r.description||'',description:r.description||'',status:r.status||'pending',sellerName:r.seller_name||'',sellerEmail:r.seller_email||'',seller_name:r.seller_name||'',seller_email:r.seller_email||'',views:r.views||0,enquiries:r.enquiries||0,hours:r.hours||'--',icon:th,photos:ph,submittedAt:r.submitted_at||r.created_at||'',submitted_at:r.submitted_at||r.created_at||'',title:[r.make,r.model,r.year?'('+r.year+')':''].filter(Boolean).join(' ')||'--'};}
function sbRowUser(r){return{id:r.id,name:r.name||'',email:r.email||'',plan:r.plan||'Essentiel',status:r.status||'active',registeredAt:r.registered_at||r.created_at||'',registered_at:r.registered_at||r.created_at||''};}
var sbRow=sbRowListing;
function fmtDate(iso){if(!iso)return'--';try{return new Date(iso).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'});}catch(e){return'--';}}
function sbEnsureUser(name,email,plan){if(!email)return;sbGet('users','email=eq.'+encodeURIComponent(email)+'&limit=1').then(function(ex){if(ex&&ex.length){if(name&&ex[0].name!==name)sbPatch('users','email=eq.'+encodeURIComponent(email),{name:name});}else{sbPost('users',{id:Date.now(),name:name||email.split('@')[0],email:email,plan:plan||'Essentiel',status:'active',registered_at:new Date().toISOString()});}}).catch(function(){});}
